#!/bin/bash

set -eo pipefail

function usage()
{
    cat <<EOF

  Usage: $prog [-h|--help]

  Display test xmessage windows in the Virginia Tech HyperCube.
  This will open a window with different messages for all X11
  16 screens in the CAVE.

  
                      OPTIONS

     -h|--help  print this help and exit

EOF
    exit 1
}

[ -n "$1" ] && usage


color=blue
lt=" LEFT EYE"
rt="RIGHT EYE"
leftOrRight="$lt"
pids=


sp='                                      '
nl='\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n   '

echo

for i in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 ; do
    d="$leftOrRight DISPLAY=:0.$i"
    ln="$nl $d $sp $d $sp $d $sp $d $sp $d"
    text="$ln $ln $ln $ln $ln $ln $ln $ln"
    export DISPLAY=:0.$i
    echo -e "$text" | xmessage -geometry 2560x1600 -fg white -bg $color -file - &
    pids="$pids $!"
    echo -e "$d    $color"

    if [ "$color" = "green" ] ; then
        color=blue
        leftOrRight="$lt"
    else
        color=green
        leftOrRight="$rt"
    fi
done

echo

function catcher()
{
    set +x
    echo -e "\n exiting\n"
    kill $pids 2> /dev/null
    exit
}


trap catcher SIGINT SIGTERM SIGQUIT

while true ; do
    wait $pids
    [ "$?" = "127" ] && catcher
done

