#!/bin/bash


function usage()
{
    cat <<EOF

  Usage: $(basename $0) [-h|--help]

  Prints raw tracker data to stdout.

  
                      OPTIONS

     -h|--help  print this help and exit

EOF
    exit 1
}

[ -n "$1" ] && usage


set -ex

exec nc -ulp 5000
