#!/bin/bash

set -exo pipefail

# The tag can be "master" or a full git check-in hash in lower case hex
# like for example:
#tag=dc184319be9a272ffa4528f5bb5d0902f1edbbbb
tag=0.2
url=https://raw.githubusercontent.com/lanceman2/quickbuild/$tag/quickbuild.make
sha512sum=d72c983ea6e308312be9b2e2503c754840c98b7d78\
f3b37c64c45d84fc844e0b4773e33ad3addf8267d84ccc626ae0\
afb41530f46769f6584da279c7fd4519e3


if [ ! -e quickbuild.make ] ; then
    wget $url -O quickbuild.make
fi

if [ -n "$sha512sum" ] ; then
    set +x
    # We wanted a particular file, so we checks it's sha512 sum.
    echo "$sha512sum  quickbuild.make" | sha512sum -c
    set -x
else
    set +x
    echo "The sha512sum of the downloaded file"
    set -x
    sha512sum quickbuild.make
fi


    
