# This is a GNU makefile with GNU make extensions

PREFIX := /usr/local/encap/hy_console-2.0


INSTALL := hy_console_logout hy_demoRunner hy_pushSshKeys


build:

install:
	mkdir -p $(PREFIX)/bin
	cp $(INSTALL) $(PREFIX)/bin

clean cleaner:

