#!/bin/bash

function usage()
{
    cat <<EOF

  Usage: $0 [-h|--help]

  Run programs needed to stop a HyperCube session from
  the remote console and then logs out.  It tries the
  best it can.

  Runs the following 2 programs (on hyperCube) via hy_stop:
      
       hy_stopx               turn off all user X sessions 
       hy_projectors_off      turn off the projectors

   and

       signal demoRunner server via ssh wget telling it to quit

   and finally

       logout on console via 'xfce4-session-logout -l'

EOF

    exit 1
}


ssh cube hy_stop

# Okay we tried

echo "logging out"
xfce4-session-logout -l

