#!/bin/bash

set -exo pipefail
cd $(dirname ${BASH_SOURCE[0]})
binDir="$PWD"
# killfile must be the same path as in
# hy_startx
source "$binDir"/hy_commonx



trap catcher SIGINT SIGTERM SIGQUIT


if [ -e "$killfile" ] ; then
    # The hy_startx script reads this file fifo for a "signal".
    #
    # This could hang if there is no process reading this fifo so
    # background it.
    #
    echo "DIE YOU RAT" >> $killfile &
    catcher
fi
